FROM golang:1.17-alpine
LABEL maintainer="Hunter Long (https://github.com/hunterlong)"
ARG VERSION
RUN apk add --update --no-cache libstdc++ gcc g++ make git ca-certificates linux-headers wget curl jq libsass nodejs npm
RUN npm install -g yarn

RUN curl -L -s https://assets.statping.com/sass -o /usr/local/bin/sass && \
    chmod +x /usr/local/bin/sass

WORKDIR /go/src/github.com/statping-ng/statping-ng

ENV IS_DOCKER=true
ENV STATPING_DIR=/go/src/github.com/statping-ng/statping-ng

EXPOSE 8585
EXPOSE 8888

ADD dev/dev-env.sh run/dev-env.sh

CMD pwd&& ls -la * && sh ./run/dev-env.sh
