version: '2.3'

services:

  statping-ng_dev:
    container_name: statping-ng_dev
    build:
      context: ../
      dockerfile: dev/Dockerfile.dev
    restart: on-failure
    volumes:
      - ./cmd:/go/src/github.com/statping-ng/statping-ng/cmd/
      - ./core:/go/src/github.com/statping-ng/statping-ng/core/
      - ./database:/go/src/github.com/statping-ng/statping-ng/database/
      - ./dev:/go/src/github.com/statping-ng/statping-ng/dev/
      - ./frontend:/go/src/github.com/statping-ng/statping-ng/frontend/
      - ./handlers:/go/src/github.com/statping-ng/statping-ng/handlers/
      - ./notifiers:/go/src/github.com/statping-ng/statping-ng/notifiers/
      - ./source:/go/src/github.com/statping-ng/statping-ng/source/
      - ./types:/go/src/github.com/statping-ng/statping-ng/types/
      - ./utils:/go/src/github.com/statping-ng/statping-ng/utils/
    environment:
      DB_CONN: sqlite
      API_SECRET: exampleapisecret
      NAME: Statping
      DOMAIN: http://localhost:8585
      DESCRIPTION: This is a dev environment with auto reloading!
      ADMIN_USER: admin
      ADMIN_PASSWORD: admin
      PORT: 8585
    ports:
      - 8888:8888
      - 8585:8585
    networks:
      - statping-ng
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8585/health || false"]
      timeout: 2s
      interval: 5s
      retries: 10

networks:
  statping-ng:
